# Slim image, multi-stage build
FROM python:3.9 as builder

WORKDIR /app
RUN pip install --upgrade pip
RUN pip install torch torchvision pillow

FROM python:3.9-slim
WORKDIR /app

# Копіюємо потрібні бібліотеки з builder
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY inference.py model.pt /app/

CMD ["python", "inference.py"]
